dbt_challenge:
  target: dev
  outputs:
    dev:
      type: mysql
      server: [server/host]
      port: [port]  # optional
      database: [schema] # optional, should be same as schema
      schema: [schema]
      username: [username]
      password: [password]
      driver: MySQL ODBC 8.0 ANSI Driver
    prod:
      type: mysql
      server: [server/host]
      port: [port]  # optional
      database: [schema] # optional, should be same as schema
      schema: [schema]
      username: [username]
      password: [password]
      driver: MySQL ODBC 8.0 ANSI Driver

dbt_project:
  target: dev
  outputs:
    dev:
      type: mysql
      server: localhost
      port: 3306  # optional
      database: my_dbt_db # optional, should be same as schema
      schema: my_dbt_db
      username: "{{ env_var('DBT_USERNAME') }}"
      password: "{{ env_var('DBT_PASSWORD') }}"
      driver: MySQL ODBC 8.0 ANSI Driver
    prod:
      type: mysql
      server: localhost
      port: 3306  # optional
      database: my_dbt_db # optional, should be same as schema
      schema: my_dbt_db
      username: "{{ env_var('DBT_USERNAME') }}"
      password: "{{ env_var('DBT_PASSWORD') }}"
      driver: MySQL ODBC 8.0 ANSI Driver
